### ISSUE TITLE
globale CSS Klasse hinzufügen

### ISSUE THREAD

**Issue by Silenz-coder** [gz-bad-erzland-p2/NextJS-Office-Sharing#10]
Inhalt:
text-white bg-office-green-500 hover:bg-office-green-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 md:px-5 md:py-2.5 focus:outline-none"

Siehe: Support Buttons, Registrieren Button

**Comment by derech1e** [comment]
Bitte mit einem `@apply` davor so:

```css
.your-name-here {
    @apply text-white bg-office-green-500 hover:bg-office-green-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lgtext-sm px-4 py-2 md:px-5 md:py-2.5 focus:outline-none
}

```
