### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Silenz-coder** [gz-bad-erzland-p2/NextJS-Office-Sharing#9]
Unhandled Runtime Error

Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

**Comment by Silenz-coder** [comment]
SyntaxError: /home/julius/Desktop/Documents/NextJS-Office-Sharing/.next/server/app-paths-manifest.json: Unexpected end of JSON input
at parse ()

**Comment by derech1e** [comment]
Wann tritt der Fehler auf??
